openapi: 3.0.3
info:
  title: 优化管理 API 端点
  description: SEO 优化执行和结果管理相关的 API 端点
  version: 1.0.0

paths:
  /api/optimizations:
    get:
      tags:
        - 优化管理
      summary: 获取优化运行记录
      description: 获取 SEO 优化运行记录列表，支持分页和过滤
      security:
        - BearerAuth: []
      parameters:
        - name: articleId
          in: query
          description: 按文章 ID 过滤
          schema:
            type: string
        - name: status
          in: query
          description: 按状态过滤
          schema:
            $ref: '../schemas/optimization.json#/components/schemas/TaskStatus'
        - name: page
          in: query
          description: 页码
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: pageSize
          in: query
          description: 每页大小
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
      responses:
        '200':
          description: 优化运行记录列表
          content:
            application/json:
              schema:
                type: object
                properties:
                  runs:
                    type: array
                    items:
                      $ref: '../schemas/optimization.json#/components/schemas/SeoRunResponse'
                  totalCount:
                    type: integer
                    description: 总记录数
                  currentPage:
                    type: integer
                    description: 当前页码
                  pageSize:
                    type: integer
                    description: 每页大小
        '401':
          description: 未认证
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: 错误信息

    post:
      tags:
        - 优化管理
      summary: 执行一次性优化
      description: 对指定文章执行一次性的 SEO 优化
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - articleId
                - llmModel
                - optimizationParams
              properties:
                articleId:
                  type: string
                  description: "Halo 文章 ID"
                llmModel:
                  type: string
                  description: "用于优化的 LLM 模型"
                  example: "gpt-3.5-turbo"
                optimizationParams:
                  $ref: '../schemas/optimization.json#/components/schemas/OptimizationParams'
      responses:
        '202':
          description: 优化任务已提交
          content:
            application/json:
              schema:
                $ref: '../schemas/optimization.json#/components/schemas/SeoRunResponse'
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: 错误信息
        '401':
          description: 未认证
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: 错误信息

  /api/optimizations/{runId}:
    get:
      tags:
        - 优化管理
      summary: 获取优化运行详情
      description: 获取指定优化运行的详细信息
      security:
        - BearerAuth: []
      parameters:
        - name: runId
          in: path
          required: true
          description: 运行记录 ID
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 优化运行详情
          content:
            application/json:
              schema:
                $ref: '../schemas/optimization.json#/components/schemas/SeoRunResponse'
        '404':
          description: 运行记录不存在
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: 错误信息
        '401':
          description: 未认证
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: 错误信息

  /api/optimizations/{runId}/report:
    get:
      tags:
        - 优化管理
      summary: 获取优化报告
      description: 获取指定优化运行的详细报告
      security:
        - BearerAuth: []
      parameters:
        - name: runId
          in: path
          required: true
          description: 运行记录 ID
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 优化报告
          content:
            application/json:
              schema:
                $ref: '../schemas/optimization.json#/components/schemas/SeoOptimizationReport'
        '404':
          description: 运行记录不存在或报告未生成
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: 错误信息
        '401':
          description: 未认证
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: 错误信息

  /api/optimizations/{runId}/apply:
    post:
      tags:
        - 优化管理
      summary: 应用优化结果
      description: 将优化结果应用到原始文章
      security:
        - BearerAuth: []
      parameters:
        - name: runId
          in: path
          required: true
          description: 运行记录 ID
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                applyMetaTitle:
                  type: boolean
                  description: "是否应用优化的元标题"
                  default: true
                applyMetaDescription:
                  type: boolean
                  description: "是否应用优化的元描述"
                  default: true
                applyKeywords:
                  type: boolean
                  description: "是否应用优化的关键词"
                  default: true
                applySlug:
                  type: boolean
                  description: "是否应用优化的 URL slug"
                  default: false
      responses:
        '200':
          description: 优化结果应用成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "优化结果应用成功"
                  appliedChanges:
                    type: object
                    properties:
                      metaTitle:
                        type: boolean
                      metaDescription:
                        type: boolean
                      keywords:
                        type: boolean
                      slug:
                        type: boolean
        '400':
          description: 优化状态不允许应用
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: 错误信息
                    example: "优化未完成或已失败"
        '404':
          description: 运行记录不存在
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: 错误信息
        '401':
          description: 未认证
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: 错误信息

  /api/optimizations/{runId}/retry:
    post:
      tags:
        - 优化管理
      summary: 重试失败的优化
      description: 重新执行失败的优化任务
      security:
        - BearerAuth: []
      parameters:
        - name: runId
          in: path
          required: true
          description: 运行记录 ID
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 重试请求已提交
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "优化重试已提交"
                  run:
                    $ref: '../schemas/optimization.json#/components/schemas/SeoRunResponse'
        '400':
          description: 优化状态不允许重试
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: 错误信息
                    example: "优化未失败或已达到最大重试次数"
        '404':
          description: 运行记录不存在
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: 错误信息
        '401':
          description: 未认证
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: 错误信息

  /api/optimizations/history/{articleId}:
    get:
      tags:
        - 优化管理
      summary: 获取文章优化历史
      description: 获取指定文章的优化历史记录
      security:
        - BearerAuth: []
      parameters:
        - name: articleId
          in: path
          required: true
          description: 文章 ID
          schema:
            type: string
        - name: limit
          in: query
          description: 返回记录数限制
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 10
      responses:
        '200':
          description: 文章优化历史
          content:
            application/json:
              schema:
                type: object
                properties:
                  articleId:
                    type: string
                    description: "文章 ID"
                  history:
                    type: array
                    items:
                      $ref: '../schemas/optimization.json#/components/schemas/SeoRunResponse'
                  totalRuns:
                    type: integer
                    description: "总优化次数"
        '404':
          description: 文章不存在或无优化记录
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: 错误信息
        '401':
          description: 未认证
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: 错误信息

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT